// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xvfbssrejzvjioexykuj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2ZmJzc3Jlanp2amlvZXh5a3VqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyOTU5NjMsImV4cCI6MjA3MTg3MTk2M30.gHuhorKxx0RdJa5Rels0cROl_Ssa6nE9BfJUtLVuBzE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});